### ISSUE TITLE
Add DATEFIREWALL to API data differences page 

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC-transition-site#146]
Census data used to have a `DATEFIREWALL` column. This is now the FAC acceptance date.

See ZD ticket [#3824](https://fac-gov.zendesk.com/agent/tickets/3824) for more specifics
```[tasklist]
### Tasks
- [x] set up local environment
- [x] meet with James P. for static site overview
- [x] add name to developers list
- [x] add datafirewall column to static site
- [x] submit for PR review
```
